# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Deploy
  displayName: Deploy to AKS
  
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'k8s-appdynamics'
          namespace: 'appdynamics'
          manifests: |
            $(Build.SourcesDirectory)/cluster-agent/cluster-agent-operator.yaml
            $(Build.SourcesDirectory)/s/cluster-agent/cluster-agent.yaml